# Generated by Django 2.2.1 on 2019-05-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import haitiApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=250, verbose_name='addressLine1')),
                ('addressLine2', models.CharField(default=None, max_length=250, verbose_name='addressLine2')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('postalCode', models.CharField(max_length=10, verbose_name='postalCode')),
                ('country', models.CharField(default='USA', max_length=250, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.TextField(max_length=50, verbose_name='totalPrice')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='isAdmin')),
                ('isVendor', models.BooleanField(default=False, verbose_name='isVendor')),
                ('isFarmer', models.BooleanField(default=False, verbose_name='isFarmer')),
                ('customerAddress', models.ManyToManyField(to='haitiApp.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True, verbose_name='orderDate')),
                ('status', models.TextField(max_length=250, verbose_name='status')),
                ('totalPrice', models.TextField(max_length=50, verbose_name='totalPrice')),
                ('customer', models.ForeignKey(on_delete=haitiApp.models.Customer, to='haitiApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(max_length=250, verbose_name='productName')),
                ('productDescription', models.TextField(max_length=250, verbose_name='productDescription')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='productPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('product', models.ForeignKey(on_delete=haitiApp.models.Product, to='haitiApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haitiApp.Order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haitiApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='cart_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haitiApp.Cart')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haitiApp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=haitiApp.models.Customer, to='haitiApp.Customer'),
        ),
    ]
