# Generated by Django 2.2.1 on 2019-05-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='orderID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='haitiApp.Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='productCart',
            field=models.ManyToManyField(to='haitiApp.Cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalPrice',
            field=models.TextField(default=0, max_length=50, verbose_name='totalPrice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='Order Received', max_length=250, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(max_length=250, unique=True, verbose_name='productName'),
        ),
        migrations.DeleteModel(
            name='cart_product',
        ),
        migrations.DeleteModel(
            name='Order_Product',
        ),
    ]
