# Generated by Django 2.2.1 on 2019-05-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0003_auto_20190513_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orderID',
        ),
        migrations.AddField(
            model_name='order',
            name='cartID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='haitiApp.Cart'),
        ),
    ]
