# Generated by Django 2.2.1 on 2019-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0004_auto_20190513_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='addressLine2'),
        ),
    ]
