# Generated by Django 2.2.1 on 2019-05-13 19:45

from django.db import migrations, models
import haitiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0004_auto_20190513_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartID',
            field=models.ForeignKey(on_delete=haitiApp.models.Cart, to='haitiApp.Cart'),
        ),
    ]
