# Generated by Django 2.2.1 on 2019-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0005_auto_20190513_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='totalPrice'),
        ),
    ]
