# Generated by Django 2.2.1 on 2019-05-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0006_auto_20190513_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
