# Generated by Django 2.2.1 on 2019-05-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haitiApp', '0007_auto_20190514_0123'),
        ('haitiApp', '0007_remove_order_totalprice'),
    ]

    operations = [
    ]
